server:
  port: 8761
spring:
  application:
    name: service-register
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0