spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: lb://user_service
            predicates:
              - Path=/api/v1/user/**
          - id: vehicle_service
            uri: lb://vehicle_service
            predicates:
              - Path=/api/v1/vehicle/**
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka